from datetime import date

MAX_LENGTH_200 = 200
MAX_COLOR_LENGTH = 7
MAX_CHAR_LENGTH_254 = 254
MAX_CHAR_LENGTH_150 = 150
PAGE_LIMIT_SIZE = 6
MEASUREMENT_UNITS_LENGTH = 10
SHOPPING_CART_FILENAME = f'shopping_cart_{date.today()}.txt'
